# Generated by Django 4.2.6 on 2023-11-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
